version: '3'

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: stikked
      MYSQL_USER: stikked
      MYSQL_PASSWORD: stikked

  stikked:
    depends_on:
      - db
    image: stikked
    env_file:
      docker/stikked-envvars.txt
    ports:
      - 80:80

volumes:
  db_data:
