version: "3.7"

services:
  nginx:
    image: nginx:1.17-alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./htdocs:/htdocs:ro
    ports:
      - 127.0.0.1:80:80/tcp

  php:
    image: stikked-php:1
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./htdocs:/htdocs
      - ./docker/stikked.php:/htdocs/application/config/stikked.php:ro
    build:
      context: ./docker/php

  mysql:
    image: mariadb:10.4
    command: mysqld --innodb-buffer-pool-size=4000000000
    volumes:
      - ./mysql-datadir_customize-in-docker-compose.yml:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stikked
      MYSQL_USER: stikked
      MYSQL_PASSWORD: stikked
